---
title: |
  Impressive climate science

abstract: |
  These are the results of a pilot study, pre-testing stimuli to strengthening trust in climate scientists. This pilot study will inform and support an intervention proposal to a megastudy.

date: today
format:
  pdf: default
  html: default
  
execute:
  echo: false
  warning: false
  message: false  
---

```{r}
library(tidyverse)
library(broom)
library(emmeans)
library(ggpubr)
library(kableExtra)
library(ggpubr)
```

```{r}
data <- readRDS("data/cleaned.rds")
```

# Descriptives

```{r}
#| label: tbl-count
#| tbl-cap: Number of participants per condition
data |> 
  count(condition) |> 
  kable()
```

```{r}
#| label: tbl-means
#| tbl-cap: Means of different outcome measures by condition

# by discipline
data %>% 
  group_by(condition) %>% 
  summarise(across(c(trust, competence, benevolence, integrity, openness, impressiveness), 
                   list(mean = ~mean(., na.rm=TRUE)), 
                   .names = "{col}_{fn}")) %>%
  mutate_if(is.numeric, ~round(.x, digits = 2)) %>% 
  kable() 
```

```{r}
# stats 

# model
model <- lm(trust ~ condition, data = data)

# Estimated marginal means
emm <- emmeans(model, ~ condition)

# Pairwise comparisons with adjustment for multiple tests
contrasts_raw <- contrast(emm, method = "pairwise", adjust = "holm") %>%
  tidy() |> 
  mutate(measure = "raw")

# Pairwise comparisons standardized as Cohen's d
contrasts_d <- eff_size(emm, sigma = sigma(model), edf = df.residual(model)) |> 
  tidy() |> 
  mutate(measure = "cohens_d")

# rename comparisons
contrasts <- bind_rows(contrasts_raw, contrasts_d) |> 
  separate(contrast, into = c("group1", "group2"), sep = " - ") |> 
  mutate(
    p_label = case_when(
      adj.p.value < 0.001 ~ "***",
      adj.p.value < 0.01  ~ "**",
      adj.p.value < 0.05  ~ "*",
      p.value < 0.001 ~ "***",
      p.value < 0.01  ~ "**",
      p.value < 0.05  ~ "*",
      TRUE ~ "ns"
    ), 
    # reverse estimates
    estimate = estimate*(-1)
  )

# get model-predicted means for plotting
predictions <- tidy(emm, 
              conf.int = TRUE) %>%
  select(condition, estimate, conf.low, conf.high)
```

```{r}
# model impressiveness
model_impressiveness <- lm(impressiveness ~ condition, data = data)
```

# Plots

```{r}
# long_format data
data_long <- data |> 
  pivot_longer(c(trust, competence, benevolence, integrity, openness), 
               names_to = "outcome", 
               values_to = "value") 
```

```{r}
#| label: fig-summary
#| fig-cap: Comparison of the different experimental groups. Asterixes represent adjusted (for multiple comparison) p-values, with adj.p.value < 0.001 ~ "\***", adj.p.value < 0.01  ~ "\**", adj.p.value <= 0.05  ~ "\*", adj.p.value > 0.05  ~ "ns" (not significant). Black dots and whiskers reprent model predictions and 95% CIs.

contrasts_raw <- contrasts |> filter(measure == "raw")

ggplot(data, aes(x = condition, y = trust)) +
  geom_boxplot(alpha = 0.5, width = 0.25, outlier.shape = NA) +
  geom_jitter(aes(color = condition), width = 0.15, alpha = 0.5, size = 2) +
  geom_pointrange(
    data = predictions, 
    aes(
      x = condition, 
      y = estimate, 
      ymin = conf.low, 
      ymax = conf.high
    ), 
    color = "black", 
    size = 0.5,
    position = position_nudge(x = 0.25)  # ⬅️ moves predictions to the right
  ) +
  labs(y = "Trust", x = "Condition") +
  scale_fill_viridis_d(option = "C", end = 0.85) +
  scale_color_viridis_d(option = "C", end = 0.85) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none") + 
  stat_pvalue_manual(
    contrasts_raw,
    label = "p_label",
    y.position = seq(max(data$trust) + 1, length.out = nrow(contrasts_raw), by = 1.5),
    xmin = "group1",
    xmax = "group2",
    tip.length = 0.01,
    step.increase = 0.05
  )
```


```{r}
#| label: fig-cohens_d
#| fig-cap: Same plot as above but reporting Cohen's d.


contrasts_d <- contrasts |> filter(measure == "cohens_d") |> 
  mutate(label_d = paste0("d = ", round(estimate, digits = 1), 
                          p_label)
         )

ggplot(data, aes(x = condition, y = trust)) +
  geom_boxplot(alpha = 0.5, width = 0.25, outlier.shape = NA) +
  geom_jitter(aes(color = condition), width = 0.15, alpha = 0.5, size = 2) +
  geom_pointrange(
    data = predictions, 
    aes(
      x = condition, 
      y = estimate, 
      ymin = conf.low, 
      ymax = conf.high
    ), 
    color = "black", 
    size = 0.5,
    position = position_nudge(x = 0.25)  # ⬅️ moves predictions to the right
  ) +
  labs(y = "Trust", x = "Condition") +
  scale_fill_viridis_d(option = "C", end = 0.85) +
  scale_color_viridis_d(option = "C", end = 0.85) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none") + 
  stat_pvalue_manual(
    contrasts_d,
    label = "label_d",
    y.position = seq(max(data$trust) + 1, length.out = nrow(contrasts_d), by = 1.5),
    xmin = "group1",
    xmax = "group2",
    tip.length = 0.01,
    step.increase = 0.05
  )
```












